name = "tup"
version = "1.0.0-rc1"

description = "acceptor pool using relay supervisor"
licences = ["Apache-2.0"]
repository = { type = "github", user = "vshakitskiy", repo = "tup" }
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[erlang]
extra_applications = ["ssl", "public_key"]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.3.0 and < 2.0.0"
relay_supervisor = ">= 1.0.0-rc1 and < 2.0.0"
# relay_supervisor = { path = "../relay-supervisor" }
logging = ">= 1.5.0 and < 2.0.0"
exception = ">= 2.1.1 and < 3.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
