name: Build docs and publish on GitHub Pages

on:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28.2"
          gleam-version: "1.18.0"
          rebar3-version: "3"

      - name: Build documentation
        run: gleam docs build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build/dev/docs/tup"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4